CC=gcc

CFLAGS = -std=c11 -Wall
LDFLAGS = -lSDL2main - lSDL2 - lSDL2_ttf - lSDL2_image - lSDL2_mixer -lm
NAME = Arkanoid

SRC = Main.c Collision.c GameManager.c HUD.c Objects.c
DEPS = Arkanoid.h

OBJS = Main.o Collision.o GameManager.o HUD.o Objects.o

.PHONY: clean

clean:
    rm -f *.o all